import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react"

export type Language = "zh" | "en"

const LANGUAGE_KEY = "alphalab-language"
const LANGUAGE_DEFAULT_VERSION_KEY = "alphalab-language-default-version"
const LANGUAGE_DEFAULT_VERSION = "3"

const translations = {
  zh: {
    "app.error": "应用出现错误",
    "app.name": "AlphaLab",
    "common.loadFailed": "加载失败",
    "common.retry": "重试",
    "common.unknownWidget": "未知组件",
    "mode.data": "数据",
    "mode.research": "研究",
    "mode.rebalance": "交易",
    "mode.tradingAshare": "纸面交易",
    "mode.data.long": "数据 - 数据中心模式",
    "mode.research.long": "研究 - 策略回测模式",
    "mode.rebalance.long": "交易 - 实盘交易模式",
    "mode.tradingAshare.long": "纸面交易 - 离线信号、风控与模拟成交",
    "mode.home": "主页",
    "mode.home.long": "主页 - 历史样本与研究概览",
    "home.indexBoard": "指数行情",
    "home.breadth": "涨跌广度",
    "home.sectorHeatmap": "行业热力图",
    "home.moneyFlow": "资金流向",
    "home.activityFlow": "成交活跃 / 资金流",
    "home.marketDetail": "行情详情",
    "home.amountProxy": "成交额代理",
    "home.turnoverProxy": "成交活跃代理",
    "home.netFlow": "净流代理",
    "home.netFlowUnavailable": "QMT 未返回可用成交额；真实净流入仍需要带买卖方向的订单流或第三方资金流数据。",
    "home.netFlowProviderMissing": "QMT/RQ 净流代理不可用",
    "home.qmtRqFlowProxy": "QMT/RQ 方向成交额代理",
    "home.proxyNetAmount": "代理净额",
    "home.proxyInflow": "方向流入",
    "home.proxyOutflow": "方向流出",
    "home.proxyNetRatio": "净额占比",
    "home.proxyMethodNote": "涨跌方向 × 成交额，仅作参考",
    "home.sectorFlowRank": "行业净流代理",
    "home.stockFlowLeaders": "个股方向净额",
    "home.ashare": "A股",
    "home.us": "美股",
    "home.connectQmt": "连接 QMT / MiniQMT 后显示实时行情",
    "home.moneyFlowAmountMissing": "QMT tick 暂未返回成交额字段",
    "home.advancers": "上涨",
    "home.decliners": "下跌",
    "home.unchanged": "平盘",
    "home.limitUp": "涨停",
    "home.limitDown": "跌停",
    "home.totalTurnover": "总成交额",
    "home.upTurnover": "上涨成交额",
    "home.downTurnover": "下跌成交额",
    "home.flatTurnover": "平盘成交额",
    "home.upTurnoverRatio": "上涨占比",
    "home.downTurnoverRatio": "下跌占比",
    "home.activeTurnover": "活跃成交",
    "home.positiveTurnover": "上涨活跃",
    "home.negativeTurnover": "下跌活跃",
    "home.equalWeight": "等权",
    "home.amountWeight": "成交额加权",
    "home.coverage": "覆盖率",
    "home.classification": "行业分类",
    "home.mapped": "已映射",
    "home.redUp": "红涨",
    "home.greenDown": "绿跌",
    "home.symbol": "代码",
    "home.close": "收盘",
    "home.change": "涨跌",
    "home.amount": "成交额",
    "home.volume": "成交量",
    "home.klineUnavailable": "暂无可用 K 线",
    "home.loadingKline": "正在读取 K 线...",
    "home.noKlineBars": "QMT/local cache 未返回可用 OHLCV",
    "home.topGainers": "领涨",
    "home.topLosers": "领跌",
    "home.rqIndustryMissing": "需要同步 RQ 行业数据",
    "home.noData": "暂无数据",
    "home.syncing": "正在同步行情数据…",
    "home.syncDone": "行情数据同步完成",
    "home.qmtStale": "QMT 日线数据滞后",
    "home.qmtProviderPending": "QMT 供应商暂未返回最新日线",
    "home.qmtDailySyncRunning": "QMT 日线同步中",
    "home.liveTicksUpdating": "实时 tick 更新中",
    "home.syncQmt": "同步 QMT 日线",
    "home.asOf": "更新于",
    "toolbar.search": "搜索",
    "toolbar.addWidget": "添加组件",
    "toolbar.saveLayout": "保存当前布局",
    "toolbar.resetLayout": "重置当前布局",
    "toolbar.help": "帮助文档",
    "toolbar.theme": "切换主题",
    "toolbar.language": "语言",
    "sidebar.workstation": "量化工作站",
    "sidebar.workflow": "当前工作流",
    "sidebar.collapse": "折叠左栏",
    "sidebar.expand": "展开左栏",
    "sidebar.statusHint": "连接状态见底栏",
    "sidebar.manageTabs": "管理标签页",
    "sidebar.manageTabsHint": "取消勾选可从侧栏隐藏；随时可在此重新显示。",
    "sidebar.manageTabsLast": "至少保留一个标签页",
    "sidebar.hideTab": "隐藏此标签",
    "task.startResearch": "开始研究",
    "task.startResearch.detail": "想法到策略草案",
    "task.runBacktest": "运行回测",
    "task.runBacktest.detail": "验证当前策略",
    "task.openEvidence": "查看证据",
    "task.openEvidence.detail": "回测结果和记录",
    "rightRail.title": "上下文侧栏",
    "rightRail.context": "上下文",
    "rightRail.agent": "Agent",
    "rightRail.activity": "动态",
    "rightRail.expand": "展开右栏",
    "rightRail.collapse": "折叠右栏",
    "rightRail.close": "关闭右栏",
    "rightRail.addSearch": "搜索/添加组件",
    "rightRail.currentContext": "当前上下文",
    "rightRail.symbol": "关注标的",
    "rightRail.strategy": "策略",
    "rightRail.backtest": "回测",
    "rightRail.mode": "当前模式",
    "rightRail.none": "未选择",
    "rightRail.unknown": "未知",
    "rightRail.connection": "连接",
    "rightRail.connected": "已连接",
    "rightRail.disconnected": "未连接",
    "rightRail.asset": "资产",
    "rightRail.dataFreshness": "数据新鲜度",
    "rightRail.needsUpdate": "需更新",
    "rightRail.ready": "正常",
    "rightRail.agentDraft": "Agent 草稿",
    "rightRail.promptPlaceholder": "写下研究想法、策略假设或下一步动作...",
    "rightRail.openAgent": "打开 AI 研究代理",
    "rightRail.v1Scope": "V1 范围",
    "rightRail.noBackend": "右栏只注入 Prompt 并聚焦 Agent；不会自动运行后端、下单或回测。",
    "rightRail.activityNow": "当前状态",
    "rightRail.riskGate": "风险门禁",
    "rightRail.liveCapable": "可实盘",
    "rightRail.paperFirst": "纸面优先",
    "rightRail.guardrails": "护栏",
    "rightRail.localOnly": "右栏只做本地上下文预览",
    "rightRail.agentNoRun": "发送后只填入并聚焦 Agent，运行需手动确认",
    "rightRail.dataNeedsReview": "数据需要复核",
    "rightRail.dataReady": "数据状态正常",
    "command.placeholder": "搜索股票、策略、组件...",
    "command.empty": "未找到匹配结果",
    "command.group.stocks": "股票",
    "command.group.modes": "切换模式",
    "command.group.widgets": "添加组件",
    "command.group.actions": "操作",
    "command.action.resetLayout": "重置当前布局",
    "command.action.toggleTheme": "切换主题",
    "command.action.startResearch": "开始研究工作流",
    "command.action.runBacktest": "运行当前策略回测",
    "command.action.openEvidence": "查看最新证据",
    "command.action.resetResearch": "重置研究工作台",
    "command.nav": "导航",
    "command.select": "选择",
    "command.close": "关闭",
    "status.qmtConnected": "QMT 已连接",
    "status.qmtDisconnected": "QMT 未连接",
    "status.monitor": "监控",
    "status.preview": "预览",
    "status.execute": "实盘",
    "status.nav": "搜索",
    "status.marketOpen": "● 交易中",
    "status.marketClosed": "○ 已收盘",
    "status.asset": "净值",
    "data.center": "数据中心",
    "data.freshness": "数据状态",
    "data.status": "状态",
    "data.snapshot": "快照",
    "data.profile": "画像",
    "data.lookup": "个股",
    "data.refresh": "刷新",
    "data.update": "更新",
    "data.needsUpdate": "需要更新",
    "data.upToDate": "已更新",
    "data.dailyStale": "日线滞后",
    "data.providerPending": "供应商等待",
    "data.liveTicks": "实时 tick",
    "data.dailySyncRunning": "日线同步中",
    "data.syncQmtDaily": "同步 QMT 日线",
    "data.liveTick": "实时 tick",
    "data.intradayMode": "日内模式",
    "data.noJob": "暂无同步任务",
    "data.job": "同步任务",
    "data.start": "起始",
    "data.latest": "最新",
    "data.expected": "期望",
    "data.coverage": "覆盖",
    "data.stockCount": "股票数",
    "data.datasetCount": "数据集",
    "data.lastSync": "上次同步",
    "data.marketPhase": "市场阶段",
    "data.fields": "QMT 字段",
    "data.tables": "RQ 表",
    "data.noData": "暂无数据",
    "data.qmt": "QMT 行情",
    "data.rq": "RiceQuant 财务",
    "data.rqTunnel": "RQ 隧道",
    "data.tunnelActive": "隧道已通",
    "data.tunnelInactive": "隧道未通",
    "data.rqConnected": "RQ 已连接",
    "data.rqDisconnected": "RQ 未连接",
    "data.connectRq": "连接 RQ",
    "data.disconnectRq": "断开 RQ",
    "data.connecting": "连接中...",
    "data.disconnecting": "断开中...",
    "data.loadingSnapshot": "读取快照中...",
    "data.loadingProfile": "读取画像中...",
    "data.loadingStock": "读取个股数据中...",
    "data.first": "首页",
    "data.last": "尾页",
    "data.both": "首尾",
    "data.optionalSymbol": "可选股票代码",
    "data.coreColumns": "核心列",
    "data.allColumns": "全部列",
    "data.rows": "行数",
    "data.columns": "列数",
    "data.nullPct": "缺失率",
    "data.size": "大小",
    "data.range": "范围",
    "data.columnNames": "列名",
    "data.qmtMatch": "QMT 匹配",
    "data.rqMatch": "RQ 匹配",
    "data.noMatch": "未匹配",
    "data.recentMarket": "近期行情",
    "data.financial": "财务",
    "data.query": "查询",
    "data.stale": "滞后",
    "data.days": "天",
    "data.syncJob": "同步任务",
    "data.table.close": "收盘价",
    "data.table.open": "开盘价",
    "data.table.high": "最高价",
    "data.table.low": "最低价",
    "data.table.volume": "成交量",
    "data.table.amount": "成交额",
    "data.table.stockInfo": "股票信息",
    "data.table.dividFactors": "除权除息",
    "data.table.income": "利润表",
    "data.table.balance": "资产负债表",
    "data.table.cashflow": "现金流量表",
    "widget.category.market": "市场概览",
    "widget.category.timing": "指数择时",
    "widget.category.backtest": "策略回测",
    "widget.category.system": "系统",
    "widget.category.trading": "实盘交易",
    "backtest.runner.title": "回测运行",
    "backtest.runner.market": "市场",
    "backtest.runner.strategy": "策略",
    "backtest.runner.start": "开始",
    "backtest.runner.end": "结束",
    "backtest.runner.notes": "备注",
    "backtest.runner.notesPlaceholder": "可选备注...",
    "backtest.runner.selectStrategy": "选择策略...",
    "backtest.runner.researchScreeners": "研究选股器",
    "backtest.runner.backtestStrategies": "可回测策略",
    "backtest.runner.valuationFlowLabel": "估值/资金流选股 (PEG/PE) [研究]",
    "backtest.runner.run": "运行回测",
    "backtest.runner.running": "运行中...",
    "backtest.runner.elapsed": "已运行",
    "backtest.runner.fullAccuracyHint": "全市场/全区间精度运行可能需要几分钟；完成后会自动载入工作台。",
    "backtest.runner.completed": "回测完成",
    "backtest.runner.failed": "回测失败",
    "backtest.runner.checkConfig": "请检查策略配置和数据",
    "backtest.runner.annualReturn": "年化收益",
    "backtest.runner.sharpe": "夏普比率",
    "backtest.runner.maxDrawdown": "最大回撤",
    "backtest.runner.cumulative": "累计收益",
    "backtest.runner.drawdown": "回撤",
    "backtest.runner.empty": "选择策略和日期范围，点击运行回测开始。",
    "backtest.runner.backtestId": "回测 ID",
    "backtest.runner.months": "个月",
    "backtest.runner.researchSelected": "已选择研究选股器",
    "backtest.runner.useResearchWidget": "点击“运行选股器”会生成研究 CSV；它不会作为交易回测执行，也不会进入实盘。",
    "backtest.strategies.title": "策略配置",
    "backtest.strategies.loadFailed": "加载策略列表失败",
    "backtest.strategies.noStrategies": "在 strategies/ 目录下创建 YAML 文件",
    "backtest.strategies.factors": "因子",
    "backtest.strategies.holdings": "持股",
    "backtest.strategies.researchOnly": "研究",
    "backtest.strategies.yamlStrategy": "策略",
    "backtest.explorer.title": "回测记录",
    "backtest.explorer.loadFailed": "加载回测记录失败",
    "backtest.explorer.empty": "暂无回测记录。运行回测后自动保存。",
    "strategies.hub.title": "策略中枢",
    "strategies.hub.loadFailed": "加载策略中枢失败",
    "strategies.hub.empty": "暂无匹配的策略",
    "strategies.hub.search": "搜索策略…",
    "strategies.hub.kind": "类型",
    "strategies.hub.status": "状态",
    "strategies.hub.all": "全部",
    "strategies.hub.kindYaml": "YAML",
    "strategies.hub.kindPorted": "移植",
    "strategies.hub.colActions": "操作",
    "strategies.hub.backtestAge": "回测时间",
    "strategies.hub.run": "回测",
    "strategies.hub.running": "运行中",
    "strategies.hub.open": "打开工作台",
    "strategies.hub.noBacktest": "无回测",
    "strategies.hub.stale": "过期",
    "strategies.hub.saved": "已保存",
    "strategies.hub.gateBlocked": "门禁拦截",
    "strategies.hub.noSignal": "无信号",
    "strategies.hub.blocked": "受阻",
    "strategies.hub.covLabel": "覆盖",
    "backtest.table.strategy": "策略",
    "backtest.table.market": "市场",
    "backtest.table.annualReturn": "年化收益",
    "backtest.table.sharpe": "夏普",
    "backtest.table.maxDrawdown": "最大回撤",
    "backtest.table.months": "月数",
    "backtest.table.start": "开始",
    "backtest.table.end": "结束",
    "backtest.table.runAt": "运行时间",
    "backtest.workbench.title": "策略收益工作台",
    "backtest.workbench.empty": "运行或选择一个回测后查看完整收益实现、风险、交易与归因。",
    "backtest.workbench.loadingLatest": "正在查找最近回测...",
    "backtest.workbench.noSaved": "当前策略还没有保存的回测，请先运行一次。",
    "backtest.workbench.loadFailed": "回测结果加载失败",
    "backtest.workbench.noData": "该回测没有可展示的收益曲线。",
    "backtest.workbench.range": "区间",
    "backtest.workbench.annualized": "年化",
    "backtest.workbench.tabs.performance": "收益",
    "backtest.workbench.tabs.risk": "风险",
    "backtest.workbench.tabs.trades": "持仓/交易",
    "backtest.workbench.tabs.attribution": "归因",
    "backtest.workbench.tabs.timing": "RSRS",
    "backtest.workbench.tabs.diagnostics": "诊断",
    "backtest.workbench.savedRun": "回测记录",
    "backtest.workbench.latestRun": "最新（默认）",
    "backtest.workbench.noSavedRuns": "暂无回测记录",
    "backtest.workbench.runNew": "运行新回测",
    "backtest.workbench.controlsHint": "选策略 → 选区间 → 运行，结果在下方标签页展示。",
    "backtest.workbench.screenerNotice": "研究选股器仅生成研究 CSV，不产生收益曲线；请在“Valuation/Flow Picks”面板查看结果。",
    "backtest.compare.title": "策略对比",
    "backtest.compare.empty": "选择 2-5 个策略进行对比（需先运行回测）",
    "backtest.compare.chartTitle": "累计收益对比（归一化 = 100）",
    "strategy.editor.title": "策略编辑器",
    "strategy.editor.choose": "选择策略",
    "strategy.editor.placeholder": "选择一个策略...",
    "strategy.editor.normalize": "归一化权重",
    "strategy.editor.validate": "验证",
    "strategy.editor.saveAs": "另存为",
    "strategy.editor.save": "保存",
    "strategy.editor.addFactor": "添加因子",
    "research.valuationFlow.title": "Valuation/Flow Stock Picks",
    "research.valuationFlow.researchOnly": "研究选股器",
    "research.valuationFlow.run": "运行选股器",
    "research.valuationFlow.running": "运行中...",
    "research.valuationFlow.runValidation": "运行验证",
    "research.valuationFlow.validating": "验证中...",
    "research.valuationFlow.refresh": "刷新",
    "research.valuationFlow.missing": "暂无选股产物。点击运行后会读取本地 QMT/RQ 数据生成 CSV。",
    "research.valuationFlow.ready": "最新研究选股已加载",
    "research.valuationFlow.validation": "样本外验证",
    "research.valuationFlow.validationMissing": "未验证",
    "research.valuationFlow.validationPassed": "验证通过",
    "research.valuationFlow.validationFailed": "验证未通过",
    "research.valuationFlow.validationReady": "验证结果已加载",
    "research.valuationFlow.validationHint": "运行验证后显示样本外收益、IC、换手和成本闸门。",
    "research.valuationFlow.validationElapsed": "验证耗时",
    "research.valuationFlow.netAnnual": "净年化",
    "research.valuationFlow.netExcess": "净超额",
    "research.valuationFlow.sharpe": "夏普",
    "research.valuationFlow.maxDrawdown": "最大回撤",
    "research.valuationFlow.turnover": "月换手",
    "research.valuationFlow.costDrag": "成本拖累",
    "research.valuationFlow.combined": "综合候选",
    "research.valuationFlow.horizon": "分周期",
    "research.valuationFlow.conviction": "高一致性",
    "research.valuationFlow.directions": "因子方向",
    "research.valuationFlow.caveats": "研究限制",
    "research.valuationFlow.asof": "截至",
    "research.valuationFlow.elapsed": "耗时",
    "research.valuationFlow.seconds": "秒",
  },
  en: {
    "app.error": "Application Error",
    "app.name": "AlphaLab",
    "common.loadFailed": "Load failed",
    "common.retry": "Retry",
    "common.unknownWidget": "Unknown widget",
    "mode.data": "Data",
    "mode.research": "Research",
    "mode.rebalance": "Trading",
    "mode.tradingAshare": "Paper",
    "mode.data.long": "Data - Data center",
    "mode.research.long": "Research - Strategy backtests",
    "mode.rebalance.long": "Trading - Live trading",
    "mode.tradingAshare.long": "Paper - offline signals, risk checks, and simulated fills",
    "mode.home": "Home",
    "mode.home.long": "Home - historical sample and research overview",
    "home.indexBoard": "Index Board",
    "home.breadth": "Market Breadth",
    "home.sectorHeatmap": "Sector Heatmap",
    "home.moneyFlow": "Money Flow",
    "home.activityFlow": "Activity & Flow",
    "home.marketDetail": "Market Detail",
    "home.amountProxy": "amount proxy",
    "home.turnoverProxy": "Turnover proxy",
    "home.netFlow": "Flow proxy",
    "home.netFlowUnavailable": "QMT did not return usable amount data. True net flow still needs signed order-flow or a dedicated provider.",
    "home.netFlowProviderMissing": "QMT/RQ flow proxy unavailable",
    "home.qmtRqFlowProxy": "QMT/RQ directional amount proxy",
    "home.proxyNetAmount": "Proxy net",
    "home.proxyInflow": "Directional inflow",
    "home.proxyOutflow": "Directional outflow",
    "home.proxyNetRatio": "Net ratio",
    "home.proxyMethodNote": "price direction x turnover; reference only",
    "home.sectorFlowRank": "Sector flow proxy",
    "home.stockFlowLeaders": "Stock directional net",
    "home.ashare": "A-Share",
    "home.us": "US",
    "home.connectQmt": "Connect QMT / MiniQMT to see live quotes",
    "home.moneyFlowAmountMissing": "QMT ticks are not returning amount fields",
    "home.advancers": "Up",
    "home.decliners": "Down",
    "home.unchanged": "Flat",
    "home.limitUp": "Limit Up",
    "home.limitDown": "Limit Down",
    "home.totalTurnover": "Total turnover",
    "home.upTurnover": "Up turnover",
    "home.downTurnover": "Down turnover",
    "home.flatTurnover": "Flat turnover",
    "home.upTurnoverRatio": "Up share",
    "home.downTurnoverRatio": "Down share",
    "home.activeTurnover": "Active turnover",
    "home.positiveTurnover": "Up active",
    "home.negativeTurnover": "Down active",
    "home.equalWeight": "Equal-weight",
    "home.amountWeight": "Amount-weighted",
    "home.coverage": "Coverage",
    "home.classification": "Classification",
    "home.mapped": "Mapped",
    "home.redUp": "Red up",
    "home.greenDown": "Green down",
    "home.symbol": "Symbol",
    "home.close": "Close",
    "home.change": "Change",
    "home.amount": "Amount",
    "home.volume": "Volume",
    "home.klineUnavailable": "K-line unavailable",
    "home.loadingKline": "Loading K-line...",
    "home.noKlineBars": "QMT/local cache returned no usable OHLCV bars",
    "home.topGainers": "Top Gainers",
    "home.topLosers": "Top Losers",
    "home.rqIndustryMissing": "Sync RQ industry data to view",
    "home.noData": "No data",
    "home.syncing": "Syncing market data…",
    "home.syncDone": "Market data sync complete",
    "home.qmtStale": "QMT daily data is stale",
    "home.qmtProviderPending": "QMT provider has not returned the latest daily bars yet",
    "home.qmtDailySyncRunning": "QMT daily sync running",
    "home.liveTicksUpdating": "Live ticks updating",
    "home.syncQmt": "Sync QMT Daily",
    "home.asOf": "as of",
    "toolbar.search": "Search",
    "toolbar.addWidget": "Add widget",
    "toolbar.saveLayout": "Save layout",
    "toolbar.resetLayout": "Reset layout",
    "toolbar.help": "Help",
    "toolbar.theme": "Toggle theme",
    "toolbar.language": "Language",
    "sidebar.workstation": "Quant workstation",
    "sidebar.workflow": "Current workflow",
    "sidebar.collapse": "Collapse sidebar",
    "sidebar.expand": "Expand sidebar",
    "sidebar.statusHint": "Connection in status bar",
    "sidebar.manageTabs": "Manage tabs",
    "sidebar.manageTabsHint": "Uncheck to hide from the sidebar; re-enable here anytime.",
    "sidebar.manageTabsLast": "At least one tab must stay visible",
    "sidebar.hideTab": "Hide this tab",
    "task.startResearch": "Start research",
    "task.startResearch.detail": "Idea to strategy draft",
    "task.runBacktest": "Run backtest",
    "task.runBacktest.detail": "Validate current strategy",
    "task.openEvidence": "View evidence",
    "task.openEvidence.detail": "Backtest results and records",
    "rightRail.title": "Context rail",
    "rightRail.context": "Context",
    "rightRail.agent": "Agent",
    "rightRail.activity": "Activity",
    "rightRail.expand": "Expand right rail",
    "rightRail.collapse": "Collapse right rail",
    "rightRail.close": "Close right rail",
    "rightRail.addSearch": "Search/add widget",
    "rightRail.currentContext": "Current context",
    "rightRail.symbol": "Focus symbol",
    "rightRail.strategy": "Strategy",
    "rightRail.backtest": "Backtest",
    "rightRail.mode": "Current mode",
    "rightRail.none": "None selected",
    "rightRail.unknown": "Unknown",
    "rightRail.connection": "Connection",
    "rightRail.connected": "Connected",
    "rightRail.disconnected": "Disconnected",
    "rightRail.asset": "Asset",
    "rightRail.dataFreshness": "Data freshness",
    "rightRail.needsUpdate": "Needs update",
    "rightRail.ready": "Ready",
    "rightRail.agentDraft": "Agent draft",
    "rightRail.promptPlaceholder": "Write a research idea, strategy hypothesis, or next action...",
    "rightRail.openAgent": "Open AI Research Agent",
    "rightRail.v1Scope": "V1 scope",
    "rightRail.noBackend": "This rail only injects a prompt and focuses the Agent; it does not auto-run backend work, orders, or backtests.",
    "rightRail.activityNow": "Current state",
    "rightRail.riskGate": "Risk gate",
    "rightRail.liveCapable": "Live capable",
    "rightRail.paperFirst": "Paper first",
    "rightRail.guardrails": "Guardrails",
    "rightRail.localOnly": "Right rail is local context preview only",
    "rightRail.agentNoRun": "Send fills and focuses Agent; running still requires manual confirmation",
    "rightRail.dataNeedsReview": "Data needs review",
    "rightRail.dataReady": "Data status ready",
    "command.placeholder": "Search stocks, strategies, widgets...",
    "command.empty": "No matching results",
    "command.group.stocks": "Stocks",
    "command.group.modes": "Switch Mode",
    "command.group.widgets": "Add Widget",
    "command.group.actions": "Actions",
    "command.action.resetLayout": "Reset current layout",
    "command.action.toggleTheme": "Toggle theme",
    "command.action.startResearch": "Start research workflow",
    "command.action.runBacktest": "Run selected strategy",
    "command.action.openEvidence": "Open latest evidence",
    "command.action.resetResearch": "Reset Research workspace",
    "command.nav": "Navigate",
    "command.select": "Select",
    "command.close": "Close",
    "status.qmtConnected": "QMT Connected",
    "status.qmtDisconnected": "QMT Disconnected",
    "status.monitor": "Monitor",
    "status.preview": "Preview",
    "status.execute": "Live",
    "status.nav": "Search",
    "status.marketOpen": "● Market open",
    "status.marketClosed": "○ Closed",
    "status.asset": "NAV",
    "data.center": "Data Center",
    "data.freshness": "Data Status",
    "data.status": "Status",
    "data.snapshot": "Snapshot",
    "data.profile": "Profile",
    "data.lookup": "Stock",
    "data.refresh": "Refresh",
    "data.update": "Update",
    "data.needsUpdate": "Needs update",
    "data.upToDate": "Up to date",
    "data.dailyStale": "Daily stale",
    "data.providerPending": "Provider pending",
    "data.liveTicks": "Live ticks",
    "data.dailySyncRunning": "Daily sync running",
    "data.syncQmtDaily": "Sync QMT Daily",
    "data.liveTick": "Live tick",
    "data.intradayMode": "Intraday mode",
    "data.noJob": "No sync job",
    "data.job": "Sync Job",
    "data.start": "Start",
    "data.latest": "Latest",
    "data.expected": "Expected",
    "data.coverage": "Coverage",
    "data.stockCount": "Stocks",
    "data.datasetCount": "Datasets",
    "data.lastSync": "Last sync",
    "data.marketPhase": "Market phase",
    "data.fields": "QMT Fields",
    "data.tables": "RQ Tables",
    "data.noData": "No data",
    "data.qmt": "QMT Market",
    "data.rq": "RQ Data",
    "data.rqTunnel": "RQ Tunnel",
    "data.tunnelActive": "Tunnel active",
    "data.tunnelInactive": "Tunnel down",
    "data.rqConnected": "RQ connected",
    "data.rqDisconnected": "RQ disconnected",
    "data.connectRq": "Connect RQ",
    "data.disconnectRq": "Disconnect RQ",
    "data.connecting": "Connecting...",
    "data.disconnecting": "Disconnecting...",
    "data.loadingSnapshot": "Loading snapshot...",
    "data.loadingProfile": "Loading profile...",
    "data.loadingStock": "Loading stock data...",
    "data.first": "First",
    "data.last": "Last",
    "data.both": "First/Last",
    "data.optionalSymbol": "Optional symbol",
    "data.coreColumns": "Core columns",
    "data.allColumns": "All columns",
    "data.rows": "Rows",
    "data.columns": "Columns",
    "data.nullPct": "Missing",
    "data.size": "Size",
    "data.range": "Range",
    "data.columnNames": "Columns",
    "data.qmtMatch": "QMT match",
    "data.rqMatch": "RQ match",
    "data.noMatch": "No match",
    "data.recentMarket": "Recent OHLCV",
    "data.financial": "Financial",
    "data.query": "Search",
    "data.stale": "Stale",
    "data.days": "days",
    "data.syncJob": "Sync Job",
    "data.table.close": "Close",
    "data.table.open": "Open",
    "data.table.high": "High",
    "data.table.low": "Low",
    "data.table.volume": "Volume",
    "data.table.amount": "Amount",
    "data.table.stockInfo": "Stock Info",
    "data.table.dividFactors": "Dividend Factors",
    "data.table.income": "Income",
    "data.table.balance": "Balance Sheet",
    "data.table.cashflow": "Cash Flow",
    "widget.category.market": "Market",
    "widget.category.timing": "Timing",
    "widget.category.backtest": "Backtest",
    "widget.category.system": "System",
    "widget.category.trading": "Trading",
    "backtest.runner.title": "Run Backtest",
    "backtest.runner.market": "Market",
    "backtest.runner.strategy": "Strategy",
    "backtest.runner.start": "Start",
    "backtest.runner.end": "End",
    "backtest.runner.notes": "Notes",
    "backtest.runner.notesPlaceholder": "Optional notes...",
    "backtest.runner.selectStrategy": "Select strategy...",
    "backtest.runner.researchScreeners": "Research screeners",
    "backtest.runner.backtestStrategies": "Backtest strategies",
    "backtest.runner.valuationFlowLabel": "PEG/PE Valuation Flow Picks [Research]",
    "backtest.runner.run": "Run Backtest",
    "backtest.runner.running": "Running...",
    "backtest.runner.elapsed": "Elapsed",
    "backtest.runner.fullAccuracyHint": "Full-universe/full-window runs can take a few minutes; the workbench will load the result when saved.",
    "backtest.runner.completed": "Backtest complete",
    "backtest.runner.failed": "Backtest failed",
    "backtest.runner.checkConfig": "Check the strategy config and data",
    "backtest.runner.annualReturn": "Annual Return",
    "backtest.runner.sharpe": "Sharpe",
    "backtest.runner.maxDrawdown": "Max Drawdown",
    "backtest.runner.cumulative": "Cumulative Return",
    "backtest.runner.drawdown": "Drawdown",
    "backtest.runner.empty": "Choose a strategy and date range, then run the backtest.",
    "backtest.runner.backtestId": "Backtest ID",
    "backtest.runner.months": "months",
    "backtest.runner.researchSelected": "Research screener selected",
    "backtest.runner.useResearchWidget": "Run Screener generates research CSVs; it is not an executable trading backtest or live strategy.",
    "backtest.strategies.title": "Strategies",
    "backtest.strategies.loadFailed": "Failed to load strategies",
    "backtest.strategies.noStrategies": "Create a YAML file under strategies/",
    "backtest.strategies.factors": "factors",
    "backtest.strategies.holdings": "holdings",
    "backtest.strategies.researchOnly": "Research",
    "backtest.strategies.yamlStrategy": "Strategy",
    "backtest.explorer.title": "Backtest Records",
    "backtest.explorer.loadFailed": "Failed to load backtest records",
    "backtest.explorer.empty": "No saved backtests yet. Runs are saved automatically.",
    "strategies.hub.title": "Strategy Hub",
    "strategies.hub.loadFailed": "Failed to load strategy hub",
    "strategies.hub.empty": "No strategies match the filters",
    "strategies.hub.search": "Search strategies…",
    "strategies.hub.kind": "Kind",
    "strategies.hub.status": "Status",
    "strategies.hub.all": "All",
    "strategies.hub.kindYaml": "YAML",
    "strategies.hub.kindPorted": "Ported",
    "strategies.hub.colActions": "Actions",
    "strategies.hub.backtestAge": "Backtest",
    "strategies.hub.run": "Run",
    "strategies.hub.running": "Running",
    "strategies.hub.open": "Open Workbench",
    "strategies.hub.noBacktest": "No backtest",
    "strategies.hub.stale": "Stale",
    "strategies.hub.saved": "Saved",
    "strategies.hub.gateBlocked": "Gate blocked",
    "strategies.hub.noSignal": "No signal",
    "strategies.hub.blocked": "Blocked",
    "strategies.hub.covLabel": "Cov",
    "backtest.table.strategy": "Strategy",
    "backtest.table.market": "Market",
    "backtest.table.annualReturn": "Annual Return",
    "backtest.table.sharpe": "Sharpe",
    "backtest.table.maxDrawdown": "Max Drawdown",
    "backtest.table.months": "Months",
    "backtest.table.start": "Start",
    "backtest.table.end": "End",
    "backtest.table.runAt": "Run Time",
    "backtest.workbench.title": "Strategy Return Workbench",
    "backtest.workbench.empty": "Run or select a backtest to inspect performance, risk, trades, and attribution.",
    "backtest.workbench.loadingLatest": "Loading latest saved backtest...",
    "backtest.workbench.noSaved": "This strategy has no saved backtest yet. Run it first.",
    "backtest.workbench.loadFailed": "Failed to load backtest results",
    "backtest.workbench.noData": "This backtest has no return curve to display.",
    "backtest.workbench.range": "Range",
    "backtest.workbench.annualized": "Annualized",
    "backtest.workbench.tabs.performance": "Performance",
    "backtest.workbench.tabs.risk": "Risk",
    "backtest.workbench.tabs.trades": "Trades",
    "backtest.workbench.tabs.attribution": "Attribution",
    "backtest.workbench.tabs.timing": "RSRS",
    "backtest.workbench.tabs.diagnostics": "Diagnostics",
    "backtest.workbench.savedRun": "Saved Run",
    "backtest.workbench.latestRun": "Latest (default)",
    "backtest.workbench.noSavedRuns": "No saved runs",
    "backtest.workbench.runNew": "Run New Backtest",
    "backtest.workbench.controlsHint": "Pick a strategy, set the range, run; results appear in the tabs below.",
    "backtest.workbench.screenerNotice": "Research screeners only generate research CSVs, not a return curve; view results in the Valuation/Flow Picks panel.",
    "backtest.compare.title": "Strategy Compare",
    "backtest.compare.empty": "Select 2-5 strategies to compare. Each needs a saved backtest.",
    "backtest.compare.chartTitle": "Cumulative Return Comparison (normalized = 100)",
    "strategy.editor.title": "Strategy Editor",
    "strategy.editor.choose": "Strategy",
    "strategy.editor.placeholder": "Select a strategy...",
    "strategy.editor.normalize": "Normalize weights",
    "strategy.editor.validate": "Validate",
    "strategy.editor.saveAs": "Save As",
    "strategy.editor.save": "Save",
    "strategy.editor.addFactor": "Add Factor",
    "research.valuationFlow.title": "Valuation/Flow Stock Picks",
    "research.valuationFlow.researchOnly": "Research screener",
    "research.valuationFlow.run": "Run Screener",
    "research.valuationFlow.running": "Running...",
    "research.valuationFlow.runValidation": "Run Validation",
    "research.valuationFlow.validating": "Validating...",
    "research.valuationFlow.refresh": "Refresh",
    "research.valuationFlow.missing": "No screener artifacts yet. Run it to generate CSVs from local QMT/RQ data.",
    "research.valuationFlow.ready": "Latest research picks loaded",
    "research.valuationFlow.validation": "OOS Validation",
    "research.valuationFlow.validationMissing": "Not validated",
    "research.valuationFlow.validationPassed": "Validation passed",
    "research.valuationFlow.validationFailed": "Validation failed",
    "research.valuationFlow.validationReady": "Validation results loaded",
    "research.valuationFlow.validationHint": "Run validation to show OOS return, IC, turnover, and cost gates.",
    "research.valuationFlow.validationElapsed": "Validation elapsed",
    "research.valuationFlow.netAnnual": "Net annual",
    "research.valuationFlow.netExcess": "Net excess",
    "research.valuationFlow.sharpe": "Sharpe",
    "research.valuationFlow.maxDrawdown": "Max drawdown",
    "research.valuationFlow.turnover": "Monthly turnover",
    "research.valuationFlow.costDrag": "Cost drag",
    "research.valuationFlow.combined": "Combined",
    "research.valuationFlow.horizon": "By Horizon",
    "research.valuationFlow.conviction": "High Conviction",
    "research.valuationFlow.directions": "Factor Directions",
    "research.valuationFlow.caveats": "Caveats",
    "research.valuationFlow.asof": "As of",
    "research.valuationFlow.elapsed": "Elapsed",
    "research.valuationFlow.seconds": "sec",
  },
} as const

export type TranslationKey = keyof typeof translations.zh

interface ElectronLanguageApi {
  getLanguage?: () => Promise<Language>
  setLanguage?: (language: Language) => Promise<Language>
  onMenuSetLanguage?: (cb: (language: Language) => void) => () => void
}

type ElectronWindow = Window & {
  api?: ElectronLanguageApi
}

interface LanguageContextValue {
  language: Language
  setLanguage: (language: Language) => void
  toggleLanguage: () => void
  t: (key: TranslationKey) => string
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

function normalizeLanguage(value: unknown, fallback: Language = "en"): Language {
  if (value === "zh" || value === "en") return value
  return fallback
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, _setLanguage] = useState<Language>(() => {
    try {
      const stored = localStorage.getItem(LANGUAGE_KEY)
      const version = localStorage.getItem(LANGUAGE_DEFAULT_VERSION_KEY)
      if (version !== LANGUAGE_DEFAULT_VERSION) {
        if (!stored) {
          localStorage.setItem(LANGUAGE_KEY, "en")
        }
        localStorage.setItem(LANGUAGE_DEFAULT_VERSION_KEY, LANGUAGE_DEFAULT_VERSION)
      }
      return normalizeLanguage(stored)
    } catch {
      return "en"
    }
  })

  const applyLanguage = useCallback((next: Language) => {
    _setLanguage(next)
    try {
      localStorage.setItem(LANGUAGE_KEY, next)
      localStorage.setItem(LANGUAGE_DEFAULT_VERSION_KEY, LANGUAGE_DEFAULT_VERSION)
    } catch { /* ignore */ }
    document.documentElement.lang = next === "zh" ? "zh-CN" : "en"
  }, [])

  const setLanguage = useCallback((next: Language) => {
    applyLanguage(next)
    const electron = (window as ElectronWindow).api
    if (electron?.setLanguage) {
      electron.setLanguage(next)
        .then((confirmed) => {
          const normalized = normalizeLanguage(confirmed, next)
          if (normalized !== next) applyLanguage(normalized)
        })
        .catch(() => {})
    }
  }, [applyLanguage])

  useEffect(() => {
    document.documentElement.lang = language === "zh" ? "zh-CN" : "en"
  }, [language])

  useEffect(() => {
    const electron = (window as ElectronWindow).api

    electron?.getLanguage?.()
      .then((value) => {
        applyLanguage(normalizeLanguage(value))
      })
      .catch(() => {})

    const cleanup = electron?.onMenuSetLanguage?.((next) => {
      applyLanguage(normalizeLanguage(next))
    })

    return () => cleanup?.()
  }, [applyLanguage])

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    toggleLanguage: () => setLanguage(language === "zh" ? "en" : "zh"),
    t: (key) => translations[language][key],
  }), [language, setLanguage])

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
